# Generated by Django 2.1.5 on 2019-01-17 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='friends',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
