# Generated by Django 2.1.5 on 2019-01-21 21:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='dice',
            field=models.CharField(default=1, max_length=255, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(default=users.models.DefaultUser, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(default=users.models.DefaultUser, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='player2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamemode',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(default=users.models.DefaultUser, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
