# Generated by Django 2.1.5 on 2019-01-17 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20190117_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemode_comment',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamemode_rating',
            name='game',
        ),
        migrations.AddField(
            model_name='gamemode_comment',
            name='game_mode',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='games.GameMode'),
        ),
        migrations.AddField(
            model_name='gamemode_rating',
            name='game_mode',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='games.GameMode'),
        ),
    ]
