# Generated by Django 2.1.5 on 2019-01-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20190117_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='validated',
        ),
        migrations.AddField(
            model_name='game',
            name='player1_cscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_cscore',
            field=models.IntegerField(default=0),
        ),
    ]
